# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicemodel',
            name='votes',
            field=models.IntegerField(default=0, editable=False, help_text='Total Votes'),
        ),
    ]
