# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170726_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
