# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170726_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicemodel',
            name='votes',
            field=models.IntegerField(default=0, help_text='Total Votes'),
        ),
    ]
