# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170727_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicemodel',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='Options / Choice'),
        ),
        migrations.AlterField(
            model_name='choicemodel',
            name='votes',
            field=models.IntegerField(default=0, help_text='Total Votes', verbose_name='Total Votes'),
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='created_date',
            field=models.DateField(verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Question Asked'),
        ),
    ]
